/** Listas literales (spec Prompt 2) — Dineros / Unidades, drawer. */

export const CONTENIDO_RECURSO_DINEROS = [
  "RCE - Recaudo Contra Entrega",
  "FCE - Flete Contra Entrega",
  "FP - Flete Pago",
] as const;

export const CONTENIDO_RECURSO_UNIDADES = [
  "Accesorios",
  "Bancos",
  "Bisutería",
  "Calzado Marroquinería",
  "Cliente no declara contenido",
  "Confección",
  "Cosméticos",
  "Documentos",
  "Libros",
  "Licor",
  "Línea Blanca",
  "Loterías",
  "MQP",
  "Notarías",
  "Medicamentos",
  "Productos para el hogar",
  "Publicidad",
  "Repuestos",
  "Tecnología",
] as const;

export const GRUPO_CIERRE_OPCIONES = [
  "Cierre final",
  "Cierre final (Solución SG en la Operación)",
  "Cierre final (Pérdida)",
  "Cierre final (Hurto)",
] as const;

export const CAUSA_UNIFICADA_DINEROS = [
  "Demora legalización reexpedidor",
  "Demora anulación RCE",
  "Pendiente devolución al remitente",
  "Pendiente inventario unidad",
  "RCE pagado, no se refleja en el sistema",
  "809. Guía mal elaborada, error en RCE",
  "Guía anulada (Unidad no recogida)",
  "N/A",
] as const;

export const CAUSA_UNIFICADA_UNIDADES: { group: string; options: string[] }[] = [
  { group: "1 — Rotulado / Etiquetas", options: [
    "1-Unidad mal rotulada o sin marcar",
    "1-Unidad con doble rotulo",
    "1-Etiquetas Trocadas",
    "1-Guía pendiente por anular",
  ]},
  { group: "2 — Despacho / Transporte", options: [
    "2-Unidad se queda dentro del Vehículo Local",
    "2-Unidad se queda dentro del Vehículo Ruta Nacional",
    "2-Unidad se queda en Origen",
    "2-Unidad llega a Destino Errado",
    "2-Unidad se despacha en otro Trailer",
    "2-Cargue de la Unidad a la Móvil Sin Guía",
  ]},
  { group: "3 — Entrega", options: [
    "3-Entrega Trocada",
    "3-Entrega Unidad Sin Guía",
    "3-Suplantación de Firma",
  ]},
  { group: "4 — Solución operativa", options: [
    "4-La Unidad si llegó, mal reporte",
    "4-MQP - Unidad es entregada directamente al cliente (no entra a Terminal Destino)",
    "4-Unidad dentro del Tiempo de Entrega",
    "4-Unidad ya Entregada al Cliente",
    "4-Unidad se queda donde el Cliente",
    "4-Se entrega unidad sellada (sellos originales)",
    "4-Se entrega unidad con guía vinculo",
    "4-Devolución al remitente con guia vinculo",
    "4-Demora por enlace",
    "4-Unidad se queda en Terminal de Enlace",
    "4-Perdida de Etiqueta",
    "4-Unidad Incautada por autoridad competente",
    "4-Unidad aprehendida por autoridad competente",
    "4-Contrabando (Unidad incautada)",
    "4-Unidad no es leída por el Sorter",
  ]},
  { group: "5 — Checkpoint", options: [
    "5-Ausencia lectura Checkpoint / Checkpoint consolidadora",
    "5-Lectura del checkpoint al interior del contenedor, furgón o en sitios sin cobertura de cámaras",
  ]},
  { group: "6-14 — Otras causas operativas", options: [
    "6-Unidad se queda por Deterioro en el Despacho",
    "7-Unidad en planilla cero o mal leída en despacho",
    "8-Averia en el transporte",
    "9-Cambio de destino",
    "10-Cliente recibe y firma, guía se pierde",
    "11-Despacho mal elaborado, anulado o repetido",
    "12-Unidad con Dummy mal Asociado",
    "13-Unidad va en Consolidadora pero no llega",
    "14-Retracto Remitente (Compra se rechaza, pero mercancía se entrega, Operaciones se entera después)",
  ]},
  { group: "15 — Seguridad externa", options: [
    "15-Atraco en vía pública con arma blanca o de fuego",
    "15-Vandalismo",
    "15-Intrusión en Sede",
  ]},
  { group: "16 — Protocolo de seguridad", options: [
    "16-Carreta Sola con Mercancía (Nadie cuida)",
    "16-Moto Sola con Maletín lleno de Mercancía (Nadie cuida)",
    "16-Descuido, Distracción, Imprudencia del Empleado / Aliado",
    "16-Entrega en dirección diferente a guía/etiqueta (Nomenclaturas dudosas)",
    "16-Entrega en la Calle / Corredor / Vía",
    "16-Mercancía al borde del furgón sin nadie afuera",
    "16-Mercancía en la cabina",
    "16-Mercancía a cuidado de terceros",
    "16-Mercancías en móvil no corresponden zona entrega y sin guía",
    "16-Móvil sola (Rompen el candado)",
    "16-No alertar cliente destino (Suplantación CM)",
    "16-No exigencia firma y CC guía destinatario",
    "16-No firma guía destinatario con CC",
    "16-No entrega al interior destinatario",
    "16-No uso de caletas para dinero recaudos en móvil",
    "16-No uso de candado, móvil en Movimiento",
    "16-No uso de candado, vehículo detenido",
    "16-No uso botón pánico ante riesgo inminente",
    "16-No uso de lazo en carreta con Mercancía",
    "16-Uso de Vanes en Rutas Riesgo alto Descuelgue",
    "16-Unidades pequeñas en carreta",
    "16-Mercancías de Alto valor, sitios marginales / invasiones",
    "16-No se identifica la unidad por cámaras",
    "16-Cargue de Unidad Deteriorada",
    "16-Ausencia de Control Personal de Seguridad",
  ]},
  { group: "17 — CCTV", options: [
    "17-Ausencia de cobertura por CCTV",
    "17-No se cuenta con grabación de CCTV para la investigación",
  ]},
  { group: "18 — Interno deshonesto", options: [
    "18-Empleado / Aliado deshonesto se apropia de la unidad",
  ]},
  { group: "20-25 — Eventos externos", options: [
    "20-Cierre de Vías",
    "21-Cargue inteligente, sin registro fotográfico",
    "22-Intrusión",
    "22-Hurto por terceros (Accidente en ruta)",
    "23-Ubicada en NyS",
    "23-Se pierde trazabilidad en NyS",
    "24-Bloqueo de vias",
    "24-Descuelgue",
    "24-Terrorismo",
    "24-Vandalismo",
    "25-Se entrega unidad a Control Salvamento con guia asociada",
  ]},
];
